version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: jada  #lägg lösenordet här
      MYSQL_DATABASE: testapp
    ports:
      - "3308:3306"
    volumes: 
      - ./mysql_init:/docker-entrypoint-initdb.d #/databasecreation.sql
      #- /mysql_init:/docker-entrypoint-initdb.d/test.sql
    container_name: mydb
    #network_mode: host
    # networks:
    #   - m7011e_default  
    # admin:
      # image: adminer
        # ports:  
          # - "3308:3306"
# # networks:
  # m7011e_default:
    # driver: bridge
