version: '3'

services:

  mydb:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: jada  #lägg lösenordet här
      MYSQL_DATABASE: antom
    ports:
      - "3308:3306"
    volumes: 
      - ./mysql_init:/docker-entrypoint-initdb.d 
    container_name: mydb