FROM node:alpine
RUN mkdir -p /app
WORKDIR /app
COPY package*.json /app/
RUN npm install
RUN npm install express-session
RUN npm i gaussian
RUN npm install request
RUN npm install --save-dev nodemon
RUN npm install mysql
RUN npm install dotenv
COPY . .
EXPOSE 8080
CMD ["npm","run", "watch"]

